name: flyflight_behavior_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - xgboost
  - lightgbm
  - tensorflow
  - keras
  - pytorch
  - gensim
  - spacy
  - nltk
  - statsmodels
  - pypdf2
  - pdfplumber
  - dask
  - geopandas
  - bokeh
  - plotly
  - umap-learn
  - hdbscan
  - pip
  - pip:
    - transformers
    - textract
